### ISSUE TITLE
아이템 32. 제네릭과 가변인수를 함께 쓸 때는 신중하라

### ISSUE THREAD

**Issue by madplay** [NMP-Study/EffectiveJava2018#32]

**Comment by iknowchang** [comment]
#####  용어 
	- varargs (가변인수) : Varargs were introduced in Java 5 and provide a short-hand for methods that support an arbitrary number of parameters of one type
##### 제네릭 varargs를 배열 매개변수로 사용하는 것은 안전하지 않다. 
예제
```
import java.util.ArrayList;
import java.util.List;

// It is unsafe to store a value in a generic varargs array parameter (Page 146)
public class Dangerus {
	// Mixing generics and varargs can violate type safety!
	static void dangerous(List<String>... stringLists) {
		List<Integer> intList = new ArrayList();
		intList.add(42);
		Object[] objects = stringLists;
		objects[0] = intList; // Heap pollution 힙 오염
		String s = stringLists[0].get(0); // ClassCastException
	}

	public static void main(String[] args) {
		List<String> stringList = new ArrayList();
		stringList.add("There be dragons!");
		dangerous(stringList);
	}
}
```
compile시 아래 경고 발생. 이유 : 실체 불가 타입으로 varargs 변수 선언
```
Information:java: Dangerus.java uses unchecked or unsafe operations.
```
run시 에러 (특별히 casting이 없는 데도 문제 발생)
```
objc[94556]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java (0x1058964c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1068a94e0). One of the two will be used. Which one is undefined.
Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at com.naver.news.m.Dangerus.dangerous(Dangerus.java:14)
	at com.naver.news.m.Dangerus.main(Dangerus.java:20)
```
#### 여기서만 제네릭 배열이 가능한 이유? (일반 코드로 선언 못함)
- 모순이 있지만 실무에서 유용함
- Arrays.asList(T.... a), Collections.addAll(Collection<? super T> c, T... elements)... 
#### compile 경고에 대한 회피 방법
- java7 전에는 방법없어 그냥 두거나, @SuppressWarnings("unchecked") 사용
- java7에서는 @SafeVargs 추가됨 (메서드 제작자가 안전함을 보장한다는 의미)
#### 안전하게 사용하려면...
	- 배열에 아무것도 저장하지 않음
	- 참조가 외부로 노출되지 않는다
	- 순수하게 값 전달로만 쓰임
#### 위의 방식으로도 안전하지 않는 경우 있음.
```
// Subtle heap pollution (Pages 147-8)
public class PickTwo {
	// UNSAFE - Exposes a reference to its generic parameter array!
	static <T> T[] toArray(T... args) {
		return args;
	}

	static <T> T[] pickTwo(T a, T b, T c) {
		switch(ThreadLocalRandom.current().nextInt(3)) {
			case 0: return toArray(a, b);
			case 1: return toArray(a, c);
			case 2: return toArray(b, c);
		}
		throw new AssertionError(); // Can't get here
	}

	public static void main(String[] args) {
		String[] attributes = pickTwo("Good", "Fast", "Cheap");
		System.out.println(Arrays.toString(attributes));
	}
}
```
Object[]를 반환하면서 ClassCastException 발생
=> 제네릭 varargs 매개변수 배열에 다른 메소드가 접근하도록 하용하면 안정하지 않다. 
=> 단, @SafeVarargs로 마크된 메소드에 넘기는 것은 안전
#### 안전하게 사용하는 예제
```
package effectivejava.chapter5.item32;

import java.util.ArrayList;
import java.util.List;

// Safe method with a generic varargs parameter (page 149)
public class FlattenWithVarargs {
    @SafeVarargs
    static <T> List<T> flatten(List<? extends T>... lists) {
        List<T> result = new ArrayList<>();
        for (List<? extends T> list : lists)
            result.addAll(list);
        return result;
    }

    public static void main(String[] args) {
        List<Integer> flatList = flatten(
                List.of(1, 2), List.of(3, 4, 5), List.of(6,7));
        System.out.println(flatList);
    }
}
```
#### 원칙!
* 제네릭이나 매개변수화 타입의 varargs 매개변수를 받는 모든 메서드에는 @SafeVarargs를 단다. 물론, 진짜 안전하게 만들어야한다!
* varargs 매개 변수에는 아무것도 저장하지 않는다. 
* 그 배열을 신뢰할 수 없는 코드에 노출하지 않는다. 
### 참고
* java8에서는 오직 정적 메소드와 final 인스턴스 메서드에만 @safeVaarargs 붙일 수 있음 (재정의 메소드 안정성 믿을 수 없으므로..)
* java9에는 private 인스턴스 메서드에도 허용
